services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev # ← Changed
    ports:
      - '3000:3000' # ← Changed to 3000 (standard dev port)
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Prevent overwriting installed dependencies
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development # ← Changed to development
      - PYTHON_PATH=/usr/bin/python3
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-network-graph}
      - PINECONE_HOST=${PINECONE_HOST}
      - PINECONE_NAMESPACE=${PINECONE_NAMESPACE:-example-namespace}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
