export interface Node {
  id: string
  label: string
  type: string
  size: number
  color: string
  summary: string
  content: string
  similarity?: number
  continent: string
  country: string
  stateProvince: string | null
  sourceType: string
  url: string
  x?: number
  y?: number
  vx?: number
  vy?: number
}

export interface Link {
  source: string
  target: string
  type: string
  strength: number
}

export const sampleNodes: Node[] = [
  {
    id: "1",
    label: "Central Hub",
    type: "hub",
    size: 20,
    color: "#15803d",
    summary: "Central processing hub for system coordination and management orchestration control",
    content:
      "The Central Hub serves as the primary coordination point for all system operations within our distributed architecture. This critical component manages the flow of information between various subsystems, ensuring optimal performance and reliability. The hub implements advanced load balancing algorithms and provides real-time monitoring capabilities. It features redundant failover mechanisms and supports horizontal scaling to accommodate growing system demands. The architecture includes sophisticated routing logic that intelligently directs traffic based on current system load and availability metrics.",
    similarity: 85,
    continent: "North America",
    country: "USA",
    stateProvince: "California",
    sourceType: "Government",
    url: "https://docs.centralhub.gov/architecture",
  },
  {
    id: "2",
    label: "Data Source A",
    type: "source",
    size: 15,
    color: "#84cc16",
    summary: "Primary data source for input stream information collection and real-time analytics",
    content:
      "Data Source A represents our primary data ingestion pipeline, responsible for collecting and processing high-volume information streams from multiple external sources. This system implements advanced data validation and cleansing algorithms to ensure data quality and consistency. The architecture supports both batch and real-time processing modes, with automatic failover capabilities to secondary data sources when needed. Integration with our analytics platform enables immediate insights and trend analysis. The system maintains comprehensive audit logs and supports data lineage tracking for compliance requirements.",
    similarity: 72,
    continent: "Europe",
    country: "Germany",
    stateProvince: null,
    sourceType: "Law Firm",
    url: "https://legal.datasource-a.de/documentation",
  },
  {
    id: "3",
    label: "Data Source B",
    type: "source",
    size: 12,
    color: "#84cc16",
    summary: "Secondary data source backup system",
    content: "Backup data ingestion system with failover capabilities and redundant processing.",
    similarity: 68,
    continent: "Europe",
    country: "France",
    stateProvince: null,
    sourceType: "NGO",
    url: "https://research.datasource-b.fr/api",
  },
  {
    id: "4",
    label: "Processing Unit",
    type: "processor",
    size: 18,
    color: "#f59e0b",
    summary: "High-performance data processing and transformation engine with machine learning capabilities",
    content:
      "The Processing Unit is a sophisticated data transformation engine that handles complex computational tasks across our distributed system. Built with modern microservices architecture, it provides scalable processing capabilities for both structured and unstructured data. The unit incorporates advanced machine learning algorithms for pattern recognition, anomaly detection, and predictive analytics. It features auto-scaling capabilities that dynamically adjust resources based on workload demands. The system supports multiple programming languages and frameworks, enabling flexible deployment of custom processing logic. Real-time monitoring and alerting ensure optimal performance and quick issue resolution.",
    similarity: 79,
    continent: "Asia",
    country: "Japan",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://tech.processing-unit.jp/docs",
  },
  {
    id: "5",
    label: "Analytics Engine",
    type: "processor",
    size: 16,
    color: "#f59e0b",
    summary: "Advanced analytics and business intelligence processing system",
    content:
      "Our Analytics Engine provides comprehensive business intelligence and data analytics capabilities. It processes large datasets to generate actionable insights and supports real-time dashboard creation. The engine includes machine learning models for predictive analytics and trend analysis.",
    similarity: 74,
    continent: "North America",
    country: "Canada",
    stateProvince: "Ontario",
    sourceType: "Government",
    url: "https://analytics.gov.ca/engine",
  },
  {
    id: "6",
    label: "Output Gateway",
    type: "gateway",
    size: 14,
    color: "#8b5cf6",
    summary: "External communication gateway for API endpoints and data export",
    content: "Gateway for external API access and data export functionality.",
    similarity: 45,
    continent: "Europe",
    country: "United Kingdom",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://api.output-gateway.co.uk/v1",
  },
  {
    id: "7",
    label: "Database Cluster",
    type: "storage",
    size: 22,
    color: "#06b6d4",
    summary: "Distributed database cluster with high availability and automatic failover mechanisms",
    content:
      "The Database Cluster represents our core data persistence layer, implementing a distributed architecture with automatic sharding and replication. This system ensures high availability through multi-region deployment and sophisticated failover mechanisms. The cluster supports both ACID transactions and eventual consistency models, depending on application requirements. Advanced indexing strategies optimize query performance across petabyte-scale datasets. The system includes automated backup and recovery procedures, with point-in-time restoration capabilities. Security features include encryption at rest and in transit, with fine-grained access controls and audit logging.",
    similarity: 82,
    continent: "North America",
    country: "USA",
    stateProvince: "Texas",
    sourceType: "Tech Company",
    url: "https://docs.database-cluster.com/architecture",
  },
  {
    id: "8",
    label: "API Gateway",
    type: "gateway",
    size: 17,
    color: "#8b5cf6",
    summary: "Main API gateway for request routing and authentication",
    content:
      "The API Gateway serves as the primary entry point for all external requests, providing authentication, rate limiting, and request routing capabilities. It implements OAuth 2.0 and JWT token validation for secure access control.",
    similarity: 58,
    continent: "Asia",
    country: "Singapore",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://api.gateway.sg/documentation",
  },
  {
    id: "9",
    label: "Cache Layer",
    type: "cache",
    size: 13,
    color: "#ef4444",
    summary: "High-speed caching layer for performance optimization",
    content: "Redis-based caching system for improved response times.",
    similarity: 35,
    continent: "Europe",
    country: "Netherlands",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://cache.tech.nl/redis",
  },
  {
    id: "10",
    label: "Load Balancer",
    type: "balancer",
    size: 15,
    color: "#10b981",
    summary: "Intelligent load balancing system with health monitoring and traffic distribution algorithms",
    content:
      "The Load Balancer implements sophisticated traffic distribution algorithms to ensure optimal resource utilization across our server infrastructure. It continuously monitors server health and automatically routes traffic away from failing instances. The system supports multiple load balancing strategies including round-robin, least connections, and weighted distribution. Advanced features include SSL termination, session persistence, and geographic routing capabilities. Real-time metrics and alerting provide visibility into traffic patterns and system performance.",
    similarity: 67,
    continent: "North America",
    country: "USA",
    stateProvince: "New York",
    sourceType: "Tech Company",
    url: "https://loadbalancer.tech.com/docs",
  },
  {
    id: "11",
    label: "Message Queue",
    type: "queue",
    size: 14,
    color: "#f97316",
    summary: "Asynchronous messaging system for inter-service communication",
    content:
      "Message Queue facilitates reliable asynchronous communication between distributed system components. It ensures message delivery guarantees and supports various messaging patterns including publish-subscribe and point-to-point communication.",
    similarity: 61,
    continent: "Europe",
    country: "Sweden",
    stateProvince: null,
    sourceType: "NGO",
    url: "https://messagequeue.opensource.se/guide",
  },
  {
    id: "12",
    label: "Search Engine",
    type: "search",
    size: 16,
    color: "#8b5cf6",
    summary: "Full-text search engine with advanced indexing and query capabilities",
    content: "Elasticsearch-based search engine providing fast full-text search across all system data.",
    similarity: 52,
    continent: "Asia",
    country: "South Korea",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://search.tech.kr/elasticsearch",
  },
  {
    id: "13",
    label: "Monitoring System",
    type: "monitor",
    size: 12,
    color: "#06b6d4",
    summary: "Comprehensive system monitoring and alerting platform with real-time metrics collection",
    content:
      "The Monitoring System provides comprehensive observability across our entire infrastructure stack. It collects metrics, logs, and traces from all system components, enabling real-time visibility into system health and performance. The platform includes customizable dashboards, intelligent alerting rules, and automated incident response capabilities. Advanced analytics help identify performance bottlenecks and predict potential issues before they impact users. Integration with popular monitoring tools and APIs enables seamless workflow automation and third-party tool connectivity.",
    similarity: 71,
    continent: "Europe",
    country: "Switzerland",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://monitoring.swiss.tech/platform",
  },
  {
    id: "14",
    label: "Security Module",
    type: "security",
    size: 19,
    color: "#dc2626",
    summary: "Advanced security module with threat detection and prevention",
    content:
      "Security Module implements multi-layered protection including intrusion detection, threat analysis, and automated response systems. It provides real-time security monitoring and compliance reporting.",
    similarity: 64,
    continent: "North America",
    country: "USA",
    stateProvince: "Virginia",
    sourceType: "Government",
    url: "https://security.gov/modules/advanced",
  },
  {
    id: "15",
    label: "Backup Service",
    type: "backup",
    size: 11,
    color: "#059669",
    summary: "Automated backup and disaster recovery service",
    content: "Automated backup system with incremental backups and disaster recovery capabilities.",
    similarity: 41,
    continent: "Europe",
    country: "Norway",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://backup.cloud.no/service",
  },
  {
    id: "16",
    label: "CDN Network",
    type: "cdn",
    size: 13,
    color: "#7c3aed",
    summary: "Global content delivery network for optimized content distribution",
    content:
      "CDN Network provides global content distribution with edge caching and intelligent routing. The system optimizes content delivery based on user location and network conditions, ensuring fast load times worldwide.",
    similarity: 48,
    continent: "North America",
    country: "USA",
    stateProvince: "California",
    sourceType: "Tech Company",
    url: "https://cdn.global.com/network",
  },
  {
    id: "17",
    label: "ML Pipeline",
    type: "ml",
    size: 18,
    color: "#f59e0b",
    summary: "Machine learning pipeline for model training and inference with automated MLOps workflows",
    content:
      "The ML Pipeline orchestrates end-to-end machine learning workflows from data preprocessing to model deployment. It supports multiple ML frameworks including TensorFlow, PyTorch, and scikit-learn. The system provides automated model versioning, A/B testing capabilities, and continuous integration for ML models. Advanced features include automated hyperparameter tuning, model performance monitoring, and drift detection. The pipeline integrates with our data infrastructure to enable seamless model training on large datasets. Real-time inference capabilities support both batch and streaming prediction scenarios.",
    similarity: 86,
    continent: "Asia",
    country: "China",
    stateProvince: null,
    sourceType: "NGO",
    url: "https://ml.research.cn/pipeline",
  },
  {
    id: "18",
    label: "Event Processor",
    type: "event",
    size: 15,
    color: "#f97316",
    summary: "Real-time event processing system for stream analytics",
    content:
      "Event Processor handles high-throughput event streams with complex event processing capabilities. It supports real-time analytics and pattern matching across distributed event sources.",
    similarity: 69,
    continent: "Europe",
    country: "Ireland",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://events.tech.ie/processor",
  },
  {
    id: "19",
    label: "Configuration Manager",
    type: "config",
    size: 10,
    color: "#6b7280",
    summary: "Centralized configuration management system",
    content: "Configuration management system for centralized settings and environment variables.",
    similarity: 33,
    continent: "Asia",
    country: "India",
    stateProvince: null,
    sourceType: "NGO",
    url: "https://config.opensource.in/manager",
  },
  {
    id: "20",
    label: "Notification Service",
    type: "notification",
    size: 12,
    color: "#8b5cf6",
    summary: "Multi-channel notification service for alerts and communications",
    content:
      "Notification Service provides multi-channel communication capabilities including email, SMS, push notifications, and webhooks. It supports template management and delivery tracking.",
    similarity: 55,
    continent: "South America",
    country: "Brazil",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://notify.tech.br/service",
  },
  {
    id: "21",
    label: "Payment Gateway",
    type: "gateway",
    size: 17,
    color: "#059669",
    summary: "Secure payment processing gateway with fraud detection and multi-currency support",
    content:
      "Payment Gateway handles secure financial transactions with advanced fraud detection algorithms and PCI DSS compliance. The system supports multiple payment methods including credit cards, digital wallets, and cryptocurrency. Real-time transaction monitoring and risk assessment ensure secure payment processing. The gateway provides comprehensive reporting and analytics for transaction tracking and financial reconciliation. Integration APIs enable seamless e-commerce platform connectivity with customizable checkout experiences.",
    similarity: 73,
    continent: "Europe",
    country: "Netherlands",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://payments.bank.nl/gateway",
  },
  {
    id: "22",
    label: "Content Manager",
    type: "content",
    size: 14,
    color: "#7c3aed",
    summary: "Digital asset management and content delivery system",
    content:
      "Content Manager provides comprehensive digital asset management with version control and automated content optimization. It supports multiple media formats and delivery channels.",
    similarity: 59,
    continent: "Europe",
    country: "Italy",
    stateProvince: null,
    sourceType: "News Article",
    url: "https://content.media.it/manager",
  },
  {
    id: "23",
    label: "Identity Provider",
    type: "identity",
    size: 16,
    color: "#dc2626",
    summary: "Centralized identity and access management system with SSO capabilities",
    content:
      "Identity Provider offers centralized authentication and authorization services with single sign-on capabilities. The system supports multiple identity protocols including SAML, OAuth, and OpenID Connect. Advanced features include multi-factor authentication, risk-based authentication, and user lifecycle management. The platform provides comprehensive audit trails and compliance reporting for regulatory requirements. Integration capabilities enable seamless connectivity with existing enterprise systems and cloud services.",
    similarity: 77,
    continent: "Europe",
    country: "Spain",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://identity.tech.es/provider",
  },
  {
    id: "24",
    label: "Workflow Engine",
    type: "processor",
    size: 15,
    color: "#f59e0b",
    summary: "Business process automation and workflow orchestration platform",
    content:
      "Workflow Engine automates complex business processes with visual workflow design and execution capabilities. It supports conditional logic, parallel processing, and human task integration for comprehensive process automation.",
    similarity: 66,
    continent: "Asia",
    country: "Australia",
    stateProvince: "New South Wales",
    sourceType: "Tech Company",
    url: "https://workflow.tech.au/engine",
  },
  {
    id: "25",
    label: "Data Warehouse",
    type: "storage",
    size: 21,
    color: "#06b6d4",
    summary: "Enterprise data warehouse for analytics and business intelligence with columnar storage optimization",
    content:
      "Data Warehouse provides enterprise-scale analytics storage with columnar optimization for complex queries. The system implements advanced data modeling techniques including star and snowflake schemas for optimal query performance. It supports both structured and semi-structured data formats with automatic schema evolution capabilities. The warehouse includes data lineage tracking, quality monitoring, and automated data governance features. Integration with popular BI tools enables self-service analytics and interactive dashboard creation. Advanced compression and partitioning strategies optimize storage costs while maintaining query performance.",
    similarity: 84,
    continent: "North America",
    country: "USA",
    stateProvince: "Washington",
    sourceType: "Tech Company",
    url: "https://datawarehouse.tech.com/enterprise",
  },
  {
    id: "26",
    label: "Log Aggregator",
    type: "monitor",
    size: 13,
    color: "#06b6d4",
    summary: "Centralized log collection and analysis system",
    content: "Log aggregation system for centralized logging with search and analysis capabilities.",
    similarity: 42,
    continent: "Europe",
    country: "Denmark",
    stateProvince: null,
    sourceType: "NGO",
    url: "https://logs.opensource.dk/aggregator",
  },
  {
    id: "27",
    label: "Scheduler Service",
    type: "processor",
    size: 11,
    color: "#f59e0b",
    summary: "Distributed task scheduling and job management system",
    content:
      "Scheduler Service manages distributed task execution with cron-like scheduling and dependency management. It provides job queuing, retry mechanisms, and failure handling for reliable task execution.",
    similarity: 56,
    continent: "Asia",
    country: "Thailand",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://scheduler.tech.th/service",
  },
  {
    id: "28",
    label: "Metrics Collector",
    type: "monitor",
    size: 12,
    color: "#06b6d4",
    summary: "Real-time metrics collection and aggregation system",
    content: "Metrics collection system for real-time performance monitoring and alerting.",
    similarity: 47,
    continent: "Africa",
    country: "South Africa",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://metrics.tech.za/collector",
  },
  {
    id: "29",
    label: "File Storage",
    type: "storage",
    size: 16,
    color: "#06b6d4",
    summary: "Distributed file storage system with versioning and access control",
    content:
      "File Storage provides scalable distributed file storage with automatic replication and versioning. The system supports fine-grained access controls and integrates with content delivery networks for optimized file distribution.",
    similarity: 63,
    continent: "Oceania",
    country: "New Zealand",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://filestorage.cloud.nz/distributed",
  },
  {
    id: "30",
    label: "Integration Hub",
    type: "hub",
    size: 19,
    color: "#15803d",
    summary:
      "Enterprise integration platform for connecting diverse systems and applications with advanced transformation capabilities",
    content:
      "Integration Hub serves as the central integration platform connecting diverse enterprise systems, applications, and data sources. The platform supports multiple integration patterns including API management, message routing, and data transformation. It provides pre-built connectors for popular enterprise applications and cloud services, enabling rapid integration deployment. Advanced features include real-time data synchronization, event-driven architecture support, and comprehensive monitoring of integration flows. The hub implements enterprise-grade security with encryption, authentication, and authorization controls. Scalable architecture ensures high availability and performance for mission-critical integration scenarios.",
    similarity: 88,
    continent: "Europe",
    country: "Belgium",
    stateProvince: null,
    sourceType: "Tech Company",
    url: "https://integration.enterprise.be/hub",
  },
]

export const sampleLinks: Link[] = [
  { source: "1", target: "2", type: "data", strength: 3 },
  { source: "1", target: "3", type: "data", strength: 3 },
  { source: "1", target: "4", type: "processing", strength: 2 },
  { source: "4", target: "5", type: "processing", strength: 4 },
  { source: "5", target: "6", type: "output", strength: 2 },
  { source: "1", target: "7", type: "storage", strength: 5 },
  { source: "8", target: "1", type: "gateway", strength: 3 },
  { source: "7", target: "9", type: "cache", strength: 2 },
  { source: "10", target: "8", type: "load", strength: 4 },
  { source: "2", target: "7", type: "storage", strength: 2 },
  { source: "3", target: "7", type: "storage", strength: 2 },
  { source: "11", target: "1", type: "messaging", strength: 3 },
  { source: "5", target: "11", type: "messaging", strength: 2 },
  { source: "12", target: "7", type: "indexing", strength: 3 },
  { source: "6", target: "12", type: "search", strength: 2 },
  { source: "13", target: "1", type: "monitoring", strength: 2 },
  { source: "13", target: "8", type: "monitoring", strength: 2 },
  { source: "13", target: "7", type: "monitoring", strength: 2 },
  { source: "14", target: "8", type: "security", strength: 4 },
  { source: "14", target: "6", type: "security", strength: 3 },
  { source: "15", target: "7", type: "backup", strength: 3 },
  { source: "16", target: "6", type: "cdn", strength: 3 },
  { source: "16", target: "10", type: "cdn", strength: 2 },
  { source: "17", target: "5", type: "ml", strength: 4 },
  { source: "17", target: "7", type: "ml", strength: 3 },
  { source: "18", target: "11", type: "event", strength: 3 },
  { source: "18", target: "1", type: "event", strength: 2 },
  { source: "19", target: "1", type: "config", strength: 2 },
  { source: "19", target: "8", type: "config", strength: 2 },
  { source: "20", target: "6", type: "notification", strength: 2 },
  { source: "20", target: "11", type: "notification", strength: 3 },
  { source: "4", target: "17", type: "processing", strength: 2 },
  { source: "9", target: "12", type: "cache", strength: 2 },
  { source: "14", target: "15", type: "security", strength: 2 },
  { source: "13", target: "20", type: "alerting", strength: 3 },
  { source: "21", target: "8", type: "payment", strength: 4 },
  { source: "21", target: "14", type: "security", strength: 5 },
  { source: "22", target: "16", type: "cdn", strength: 3 },
  { source: "22", target: "7", type: "storage", strength: 2 },
  { source: "23", target: "14", type: "security", strength: 4 },
  { source: "23", target: "8", type: "identity", strength: 3 },
  { source: "6", target: "21", type: "payment", strength: 2 },
  { source: "6", target: "22", type: "content", strength: 2 },
  { source: "24", target: "1", type: "workflow", strength: 3 },
  { source: "24", target: "11", type: "messaging", strength: 2 },
  { source: "25", target: "7", type: "storage", strength: 4 },
  { source: "25", target: "5", type: "analytics", strength: 5 },
  { source: "26", target: "13", type: "monitoring", strength: 3 },
  { source: "26", target: "7", type: "storage", strength: 2 },
  { source: "27", target: "1", type: "scheduling", strength: 2 },
  { source: "27", target: "4", type: "processing", strength: 3 },
  { source: "28", target: "13", type: "monitoring", strength: 4 },
  { source: "28", target: "10", type: "load", strength: 2 },
  { source: "29", target: "7", type: "storage", strength: 3 },
  { source: "29", target: "22", type: "content", strength: 4 },
  { source: "30", target: "1", type: "integration", strength: 5 },
  { source: "30", target: "8", type: "gateway", strength: 3 },
  { source: "30", target: "21", type: "payment", strength: 2 },
  { source: "30", target: "23", type: "identity", strength: 3 },
  { source: "17", target: "25", type: "ml", strength: 4 },
  { source: "18", target: "27", type: "event", strength: 2 },
  { source: "24", target: "18", type: "workflow", strength: 3 },
  { source: "25", target: "17", type: "analytics", strength: 3 },
  { source: "26", target: "28", type: "monitoring", strength: 2 },
  { source: "29", target: "15", type: "backup", strength: 3 },
  { source: "30", target: "24", type: "integration", strength: 4 },
  { source: "3", target: "25", type: "data", strength: 2 },
  { source: "5", target: "28", type: "analytics", strength: 2 },
  { source: "9", target: "29", type: "cache", strength: 2 },
  { source: "12", target: "26", type: "search", strength: 2 },
  { source: "14", target: "30", type: "security", strength: 3 },
  { source: "16", target: "29", type: "cdn", strength: 2 },
  { source: "19", target: "27", type: "config", strength: 3 },
  { source: "20", target: "24", type: "notification", strength: 2 },
]
