name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t network-graph-search .

      # TODO: Add tests after UAT phase
      # - name: Run tests
      #   run: docker run network-graph-search pnpm test
